# Generated by Django 5.0.2 on 2025-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_audio/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='audio_generation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
